### ISSUE TITLE
fails to build with text-2.1.2

### ISSUE THREAD

**Issue by juhp** [ismailmustafa/handwriting-haskell#1]
For Stackage Nightly with ghc-9.10.2:

```
       Building library for handwriting-0.1.0.3...                                                            12:58:25 [5744/954403]
       [1 of 3] Compiling Network.Internal.Model
       /home/curators/work/unpack-dir/unpacked/handwriting-0.1.0.3-b0b0809228d4c929b63ead48744ec9cf04c4c0b0ca348df88f83860b5a24cbeb/
src/Network/Internal/Model.hs:58:44: error: [GHC-87543]
           Ambiguous occurrence ‘show’.
           It could refer to
              either ‘Prelude.show’,
                     imported from ‘Prelude’ at src/Network/Internal/Model.hs:16:8-29
                     (and originally defined in ‘ghc-internal-9.1002.0:GHC.Internal.Show’),
                  or ‘Data.Text.show’,
                     imported from ‘Data.Text’ at src/Network/Internal/Model.hs:29:1-16.
          |
       58 |     <> mconcat ["       Handwriting Id: ", show a, "\n"]  
          |                                            ^^^^
        
       /home/curators/work/unpack-dir/unpacked/handwriting-0.1.0.3-b0b0809228d4c929b63ead48744ec9cf04c4c0b0ca348df88f83860b5a24cbeb/
src/Network/Internal/Model.hs:59:44: error: [GHC-87543]
           Ambiguous occurrence ‘show’.
           It could refer to
              either ‘Prelude.show’,
                     imported from ‘Prelude’ at src/Network/Internal/Model.hs:16:8-29
                     (and originally defined in ‘ghc-internal-9.1002.0:GHC.Internal.Show’),
                  or ‘Data.Text.show’,
                     imported from ‘Data.Text’ at src/Network/Internal/Model.hs:29:1-16.
          |
       59 |     <> mconcat ["                Title: ", show b, "\n"]
          |                                            ^^^^
        
       /home/curators/work/unpack-dir/unpacked/handwriting-0.1.0.3-b0b0809228d4c929b63ead48744ec9cf04c4c0b0ca348df88f83860b5a24cbeb/
src/Network/Internal/Model.hs:60:44: error: [GHC-87543]
           Ambiguous occurrence ‘show’.
           It could refer to
              either ‘Prelude.show’,
                     imported from ‘Prelude’ at src/Network/Internal/Model.hs:16:8-29
                     (and originally defined in ‘ghc-internal-9.1002.0:GHC.Internal.Show’),
                  or ‘Data.Text.show’,
                     imported from ‘Data.Text’ at src/Network/Internal/Model.hs:29:1-16.
          |
       60 |     <> mconcat ["         Date Created: ", show c, "\n"]
          |                                            ^^^^
:
```
